export const USER_LOGIN = 'USER_LOGIN';

export const CREATE_PROJECT = 'CREATE_PROJECT';

export const CREATE_INTERFACE = 'CREATE_INTERFACE';

// export const GET_PROJECT_INTERFACES = 'GET_PROJECT_INTERFACES';

